# Generated by Django 4.2.2 on 2025-05-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("CustomerID", models.AutoField(primary_key=True, serialize=False)),
                ("FirstName", models.CharField(max_length=50)),
                ("LastName", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=254, unique=True)),
                ("Password", models.CharField(max_length=255)),
                ("PhoneNumber", models.CharField(max_length=20)),
                ("RegistrationDate", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
